package io.github.x051130x.signindustry;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.block.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.util.Identifier;
import net.minecraft.util.registry.Registry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
public class Signindustry implements ModInitializer {

    public static final String MODID = "signindustry";
    public static final Logger LOGGER = LoggerFactory.getLogger(MODID);
    public static final signstatic PILLAR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNCIRCLENOTALLOW = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNORDERFWD = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNORDERLEFT = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNORDERRIGHT = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNORDERBOTH = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNINJUNCTION = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNINJUNCTIONSTOP = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNINJUNCTIONLONGSTOP = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SECONDARYSIGNCAR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNSTOP = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNCROSSFIRST = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOCAR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOHOUSE = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOLARGEBUS = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOMAN = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOMANCAR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOMANTHREE = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOMOCAR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOMOTO = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOMOTOBIKE = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOSMALLCAR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOTHREE = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOTHREECAR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOTHREECAR2 = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOTRACTOR = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOTRAILER = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOTRUCK = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    public static final signstatic SIGNNOWHISTLE = new signstatic(FabricBlockSettings.of(Material.METAL).strength(4.0f));
    @Override
    public void onInitialize() {
        LOGGER.info("Hello SignIndustry!");

        Registry.register(Registry.BLOCK, new Identifier(MODID, "pillar"), PILLAR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "pillar"), new BlockItem(PILLAR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signcirclenotallow"), SIGNCIRCLENOTALLOW);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signcirclenotallow"), new BlockItem(SIGNCIRCLENOTALLOW, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signorderfwd"), SIGNORDERFWD);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signorderfwd"), new BlockItem(SIGNORDERFWD, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signorderleft"), SIGNORDERLEFT);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signorderleft"), new BlockItem(SIGNORDERLEFT, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signorderright"), SIGNORDERRIGHT);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signorderright"), new BlockItem(SIGNORDERRIGHT, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signorderboth"), SIGNORDERBOTH);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signorderboth"), new BlockItem(SIGNORDERBOTH, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signinjunction"), SIGNINJUNCTION);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signinjunction"), new BlockItem(SIGNINJUNCTION, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signinjunctionstop"), SIGNINJUNCTIONSTOP);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signinjunctionstop"), new BlockItem(SIGNINJUNCTIONSTOP, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signinjunctionlongstop"), SIGNINJUNCTIONLONGSTOP);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signinjunctionlongstop"), new BlockItem(SIGNINJUNCTIONLONGSTOP, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "secondarysigncar"), SECONDARYSIGNCAR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "secondarysigncar"), new BlockItem(SECONDARYSIGNCAR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signstop"), SIGNSTOP);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signstop"), new BlockItem(SIGNSTOP, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signcrossfirst"), SIGNCROSSFIRST);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signcrossfirst"), new BlockItem(SIGNCROSSFIRST, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnocar"), SIGNNOCAR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnocar"), new BlockItem(SIGNNOCAR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnohouse"), SIGNNOHOUSE);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnohouse"), new BlockItem(SIGNNOHOUSE, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnolargebus"), SIGNNOLARGEBUS);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnolargebus"), new BlockItem(SIGNNOLARGEBUS, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnoman"), SIGNNOMAN);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnoman"), new BlockItem(SIGNNOMAN, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnomancar"), SIGNNOMANCAR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnomancar"), new BlockItem(SIGNNOMANCAR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnomanthree"), SIGNNOMANTHREE);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnomanthree"), new BlockItem(SIGNNOMANTHREE, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnomocar"), SIGNNOMOCAR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnomocar"), new BlockItem(SIGNNOMOCAR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnomoto"), SIGNNOMOTO);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnomoto"), new BlockItem(SIGNNOMOTO, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnomotobike"), SIGNNOMOTOBIKE);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnomotobike"), new BlockItem(SIGNNOMOTOBIKE, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnosmallcar"), SIGNNOSMALLCAR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnosmallcar"), new BlockItem(SIGNNOSMALLCAR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnothree"), SIGNNOTHREE);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnothree"), new BlockItem(SIGNNOTHREE, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnothreecar"), SIGNNOTHREECAR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnothreecar"), new BlockItem(SIGNNOTHREECAR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnothreecar2"), SIGNNOTHREECAR2);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnothreecar2"), new BlockItem(SIGNNOTHREECAR2, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnotractor"), SIGNNOTRACTOR);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnotractor"), new BlockItem(SIGNNOTRACTOR, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnotrailer"), SIGNNOTRAILER);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnotrailer"), new BlockItem(SIGNNOTRAILER, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnotruck"), SIGNNOTRUCK);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnotruck"), new BlockItem(SIGNNOTRUCK, new FabricItemSettings()));
        Registry.register(Registry.BLOCK, new Identifier(MODID, "signnowhistle"), SIGNNOWHISTLE);
        Registry.register(Registry.ITEM, new Identifier(MODID, "signnowhistle"), new BlockItem(SIGNNOWHISTLE, new FabricItemSettings()));
    }
}
